<li class="link my-account-link custom-account">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <img src="<?= $block->getViewFileUrl('images/account_icon.png'); ?>" 
    
             alt="<?= $escaper->escapeHtml($block->getLabel()) ?>"/>
        <?= $escaper->escapeHtml($block->getLabel()) ?>
    </a>
    <li class="link my-account-link">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
</li>
</li>
