<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>


<header class="page-header">
    <div class="inner_container">
        <div class="header content">
            <div class="logo">
                <a href="<?= $block->getUrl('') ?>"> 
                    <img src="<?= $block->getViewFileUrl('images/logo_header.png') ?>" alt="" />
                </a> 
            </div>
            <div class="wallan">
                <span>hyundai wallan</span>
            </div>
        </div>
    </div>
</header>
