<div class="three_col_block section_padding block_content">
  <h2>Special offers</h2>
  <p>Our mission is to make your whole buying experience as seamless as possible.</p>
  <ul>
    <li> <a href="#"> <img src="images/special_offer-img-1.jpg" alt=""> </a>
      <h3><a href="#">Free filters</a> </h3>
      <p>On periodic maintenance</p>
    </li>
    <li> <a href="#"> <img src="images/special_offer-img-2.jpg" alt=""> </a>
      <h3><a href="#">Save 151 RIYALS</a></h3>
      <p>On your periodic maintenance</p>
    </li>
    <li> <a href="#"> <img src="images/special_offer-img-3.jpg" alt=""> </a>
      <h3><a href="#">Hyundai care</a></h3>
      <p>with fitness time club</p>
    </li>
  </ul>
  <div class="more_btn"> <a href="#">Explore more offers</a> </div>
</div>