                <ul>
                    <li><a href="<?= $block->getUrl('vehicle-line-up') ?>"><?= __('Vehicle line-up') ?></a></li>
                    <li><a href="<?= $block->getUrl('downloads') ?>"><?= __('Downloads') ?></a></li>
                    <li><a href="<?= $block->getUrl('legal') ?>"><?= __('Legal') ?></a></li>
                    <li><a href="<?= $block->getUrl('contact') ?>"><?= __('Contact us') ?></a></li>
                    <li><a href="<?= $block->getUrl('news-alerts') ?>"><?= __('News alerts') ?></a></li>
                    <li><a href="<?= $block->getUrl('site-map') ?>"><?= __('Site map') ?></a></li>
                </ul>
