<div class="owl-carousel owl-theme" id="banner_carousel">
    <div class="item slider" style="background-image: url('<?= $block->getViewFileUrl('images/home_banner-img.jpg') ?>');">
        <div class="overlay_content">
            <h1>Easiest way to buy a Hyundai in Saudi Arabia</h1>
            <a href="#">Explore models & buy</a>
        </div>
    </div>
    <!-- <div class="item slider" style="background-image: url('<?= $block->getViewFileUrl('images/banner-img.jpg') ?>');"> -->
        <div class="item slider" style="background-image: url('<?= $block->getViewFileUrl('images/home_banner-img.jpg') ?>');">
        <div class="overlay_content">
            <h1>Find Your Dream Car with Us</h1>
            <a href="#">Discover More</a>
        </div>
    </div>
    <!-- <div class="item slider" style="background-image: url('<?= $block->getViewFileUrl('images/banner-img.jpg') ?>');"> -->
        <div class="item slider" style="background-image: url('<?= $block->getViewFileUrl('images/home_banner-img.jpg') ?>');">
        <div class="overlay_content">
            <h1>Experience Hyundai Like Never Before</h1>
            <a href="#">Book a Test Drive</a>
        </div>
    </div>
</div>

<!-- <script type="text/javascript">
    require(['jquery', 'owlcarousel'], function($) {
        $(document).ready(function() {
            if ($.fn.owlCarousel) {
                $('#banner_carousel').owlCarousel({
                    loop: true,
                    margin: 10,
                    nav: true,
                    dots: true,
                    autoplay: true,
                    autoplayTimeout: 4000,
                    autoplayHoverPause: true,
                    items: 1,
                    navText: ['<span class="prev">&#10094;</span>', '<span class="next">&#10095;</span>']
                });
            } else {
                console.error('Owl Carousel failed to load.');
            }
        });
    });
</script> -->

<!-- <script type="text/x-magento-init">
{
    "*": {
        "js/banner-carousel": {}
    }
}
</script> -->




