<div class="col">
                    <div class="title article-title"><i></i> <?= __('About us') ?></div>
                    <ul class="accordion-content">
                        <li><a href="<?= $block->getUrl('about-wallan') ?>"><?= __('About Wallan') ?></a></li>
                        <li><a href="<?= $block->getUrl('about-hyundai') ?>"><?= __('About Hyundai') ?></a></li>
                        <li><a href="<?= $block->getUrl('news') ?>"><?= __('News') ?></a></li>
                    </ul>
                </div>