
<div class="col">
                    <div class="title article-title"><i></i> <?= __('Contact & Sales') ?></div>
                    <ul class="accordion-content">
                        <li><a href="<?= $block->getUrl('special-offer') ?>"><?= __('Special offer') ?></a></li>
                        <li><a href="<?= $block->getUrl('contact') ?>"><?= __('Contact us') ?></a></li>
                        <li><a href="<?= $block->getUrl('book-test-drive') ?>"><?= __('Book a test drive') ?></a></li>
                        <li><a href="<?= $block->getUrl('view-vehicles') ?>"><?= __('View all vehicles') ?></a></li>
                        <li><a href="<?= $block->getUrl('request-callback') ?>"><?= __('Request a callback') ?></a></li>
                        <li><a href="<?= $block->getUrl('faq') ?>"><?= __('FAQ') ?></a></li>
                    </ul>
                </div>