<div class="col">
                    <div class="title article-title"><i></i> <?= __('Hyundai Wallan Social Media') ?></div>
                    <ul class="social_media_link accordion-content">
                        <li><a href="#"><img src="<?= $block->getViewFileUrl('images/footer_fb-icon.png') ?>" alt=""></a></li>
                        <li><a href="#"><img src="<?= $block->getViewFileUrl('images/footer_twitter-icon.png') ?>" alt=""></a></li>
                        <li><a href="#"><img src="<?= $block->getViewFileUrl('images/footer_insta-icon.png') ?>" alt=""></a></li>
                    </ul>
                </div>